# Configuration file for Notion Helper
# Copy this to config.yaml and fill in your actual values

# Notion API Configuration
notion:
    token: "YOUR_NOTION_INTEGRATION_TOKEN"
    project_database_id: "YOUR_PROJECT_DATABASE_ID"
    daily_log_page_id: "YOUR_DAILY_LOG_PAGE_ID"

# iCloud configuration
icloud:
    username: "your_icloud_email@example.com"
    app_password: "your_app_specific_password" # Generate from Apple ID settings
    calendars: # List of calendar names to sync (empty list means all calendars)
        - "Calendar"
        - "Work"
        - "Personal"

# File paths
paths:
    email_template: "email_template.txt" # Email template file

# Email configuration
email:
    to_list:
        - "recipient1@example.com"
        - "recipient2@example.com"
    cc_list:
        - "cc1@example.com"
        - "cc2@example.com"
    your_name: "Your Name"
    subject_template: "Weekly Update - {week_start} to {week_end}"

# DeepSeek AI configuration for email polishing
deepseek:
    api_key: "YOUR_DEEPSEEK_API_KEY"  # Get from https://platform.deepseek.com
    model: "deepseek-chat"
    temperature: 0.7
    max_tokens: 2000

# Timezone
timezone: "Asia/Shanghai" # China Time

# Recurring
recurring_events:
    Monday:
        - title: "Weekly Team Meeting"
          time: "10:00-11:00"
    Tuesday:
        - title: "Gym"
          time: "18:00-19:00"
    Wednesday:
        - title: "Project Sync"
          time: "14:00-15:00"
    Thursday:
        - title: "Code Review"
          time: "16:00-17:00"
    Friday:
        - title: "Client Call"
          time: "15:00-16:00"
    Saturday:
        - title: "Gym"
          time: "10:00-11:00"
    Sunday:
        - title: "Family Dinner"
          time: "18:00-19:00"
